apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
  labels:
    ActiveMQArtemis: ex-aao
    application: ex-aao-app
spec:
  # Add fields here
  size: 4
  image: registry.redhat.io/amq7/amq-broker:7.4
  clusterConfig:
    clusterUserName: clusteruser
    clusterPassword: clusterpass
  commonConfig:
    userName: admin
    password: admin

