apiVersion: broker.amq.io/v1alpha1
kind: ActiveMQArtemis
metadata:
  name: example-activemqartemis
  labels:
    ActiveMQArtemis: example-activemqartemis
    application: example-activemqartemis-app
spec:
  # Add fields here
  size: 1
  image: kibiluzbad/artemis-broker:7.4
  commonConfig:
    userName: admin
    password: admin

