apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
  labels:
    ActiveMQArtemis: ex-aao
    application: ex-aao-app
spec:
  # Add fields here
  size: 1
  image: kibiluzbad/artemis-broker:7.4
  commonConfig:
    userName: admin
    password: admin

