apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: activemqartemisusers.broker.amq.io
spec:
  group: broker.amq.io
  names:
    kind: ActiveMQArtemisUser
    listKind: ActiveMQArtemisUserList
    plural: activemqartemisusers
    singular: activemqartemisuser
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha2
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            statefulsetName:
              type: string
            userName:
              type: string
            password:
              type: string
            roles:
              type: string
          required:
            - userName
            - password
            - roles
          type: object
        status:
          type: object
  versions:
  - name: v1alpha2
    served: true
    storage: true
  - name: v2alpha1
    served: true
    storage: false