apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: activemqartemissecuritysettings.broker.amq.io
spec:
  group: broker.amq.io
  names:
    kind: ActiveMQArtemisSecuritySetting
    listKind: ActiveMQArtemisSecuritySettingList
    plural: activemqartemissecuritysettings
    singular: activemqartemissecuritysetting
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha2
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            statefulsetName:
              type: string
            addressMatch:
              type: string
            send:
              type: string
            consume:
              type: string
            createDurableQueueRoles:
              type: string
            deleteDurableQueueRoles:
              type: string
            createNonDurableQueueRoles:
              type: string
            deleteNonDurableQueueRoles:
              type: string
            manage:
              type: string
          required:
            - addressMatch
          type: object
        status:
          type: object
  versions:
  - name: v1alpha2
    served: true
    storage: true
  - name: v1alpha1
    served: true
    storage: false